Comments and new features in the excel generation
recski/brise-plandok pull request #5
Opened 2021-07-23 12:21 UTC by adaamko

2021-07-26 08:18 UTC, adaamko commented on brise_plandok/annotation/attributes.py
> +    os.path.dirname(os.path.abspath(__file__)), 'merkmale_categories.csv')
@recski I've added 'merkmale_categories.csv' to this folder (it wasn't pushed in to sample_data), and also changed the path to load it from there. I think it might be better in this directory. Let me know your thoughts on this!

2021-07-26 08:19 UTC, adaamko commented on brise_plandok/convert.py
>              else:
I also added an attribute check here, but I see you also added one to the eval_attr_ext.py file. Do you think we should keep both?

2021-07-29 07:59 UTC, recski commented on brise_plandok/annotation/attributes.py
> +    os.path.dirname(os.path.abspath(__file__)), 'merkmale_categories.csv')
absolutely, sample_data was never a good place for it :) thanks!

2021-07-29 08:09 UTC, recski commented on brise_plandok/convert.py
>              else:
yes, sure, the more sanity checks, the better :)

2021-07-29 08:11 UTC, recski commented on brise_plandok/convert.py
> +                    logging.warning(f'Sen ID: {curr_sen["sen_id"]}, Attribute: {attribute["name"]} not in the Attribute list')
but maybe put this in a function so as not to have the same 3 lines of code twice

2021-07-29 08:22 UTC, recski requested changes
see inline comments

2021-07-30 15:01 UTC, adaamko commented on brise_plandok/convert.py
> +                    logging.warning(f'Sen ID: {curr_sen["sen_id"]}, Attribute: {attribute["name"]} not in the Attribute list')
Thanks, done!

2021-07-30 15:01 UTC, adaamko commented
@recski Added xlsx to xlsx conversion!

2021-08-02 05:32 UTC, recski approved these changes

2021-08-02 05:32 UTC, merged